steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cryptopay-api:$SHORT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cryptopay-api:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cryptopay-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cryptopay-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production'
      - '--set-cloudsql-instances'
      - '${PROJECT_ID}:us-central1:cryptopay-db'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:us-central1:cryptopay-db'

images:
  - 'gcr.io/$PROJECT_ID/cryptopay-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
